Bit plane encoder
oresat/oresat-linux-app-framework pull request #18
Opened 2023-09-22 19:05 UTC by kk60503

Still working on binding

2023-09-23 00:42 UTC, ryanpdx reviewed
Looks good, some clean up and changes to binding code needed.

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/bpe.cpp
> +                                            unsigned int, unsigned char>());
This should be:
```
py::class_<BitStream>(m, "Bitstream")
        .def(py::init<>())
        .def_readonly("SegBitCounter", &BitStream::SegBitCounter)
        .def_readonly("TotalBitCounter", &BitStream::TotalBitCounter)
        .def_readonly("ByteBitCounter", &BitStream::ByteBuffer_4Bytes)
        .def_readonly("CodeWordAlighmentBits", &BitStream::CodeWordAlighmentBits)
        .def_readonly("CodeWord_Length", &BitStream::CodeWord_Length)
        .def_readonly("F_Bits", &BitStream::F_Bits);
```

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/bpe.cpp
> +#include "pybind11/pybind11.h"
This is a global include, so use "<" and ">"

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/bpe.cpp
> +#include <iostream>
No needed

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/bpe.cpp
> +#include <string>
Not needed

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/bpe.cpp
> +#include "source/main_pybind.h"
Shouldn't this be `"source/globals.h"`?

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/bpe.cpp
> +using namespace pybind11::literals;
Is this needed?

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/makefile
> +#Makefile for binding bpe C code to Python
Should be Makefile not makefile.

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/README.rtf
> +
Remove my name and add a link to the website.

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/makefile
> +# CCSDS image compression standard makefile for usage compiling as C code
Makefile not makefile

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/UNL_readme_kielymods.rtf
> +{\rtf1\mac\ansicpg10000\cocoartf824\cocoasubrtf480
Use the txt version, not rtf one

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/UNL_readme_kielymods.rtf
> +{\rtf1\mac\ansicpg10000\cocoartf824\cocoasubrtf480
The pdf is not needed.

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/README.rtf
> +
Use md not rtf

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/pixel_check.py
> +# pixel_check.py: a simple program for comparing/checking each pixel in identical images
Remove this

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/main_pybind.h
> +// Header file including global.h plus binding declarations
Why does this exist, isn't it just `globals.h`?

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/makefile
> +CPPFLAGS = \
Rename to `INC_DIRS`

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/cfc.py
> +# A simple program to convert raw cfc images to viewable file types
Remove this

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/errorhandle.c
> +#endif
This give compile errors

```
source/errorhandle.c: In function ‘DebugInfo’:
source/errorhandle.c:48:9: error: format not a string literal and no format arguments [-Werror=format-security]
   48 |         fprintf(stderr, m);
      |         ^~~~~~~
```

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/source/errorhandle.c
> +#endif
Commenting out #define DEBUG fixes it

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/makefile
> +		  #$(shell python3 -m pybind11 --includes)
Remove

2023-09-23 00:42 UTC, ryanpdx commented on olaf/bpe/makefile
> +		  -undefined dynamic_lookup \
Code won't compile with this flag on my system. If it is removed, it compiles just fine.

2023-11-14 03:03 UTC, ryanpdx requested changes
- Remove all `.pyc` files
- move `olaf/bpe/testing/` contents  to the `tests/bpe/`
- move all images out of the `olaf/` dir
- What are the `GHplaceholder` files

2023-11-14 03:03 UTC, ryanpdx commented on olaf/bpe/testing/test_bpe.py
> +
Remove, main is not required for unit tests

2023-11-14 03:03 UTC, ryanpdx commented on olaf/bpe/testing/test_bpe.py
> +
Use """ comment sytle for all docstrings

2023-11-14 03:03 UTC, ryanpdx commented on olaf/bpe/testing/test_bpe.py
> +# testing suite for bpe python module
change to """ comment style

2023-11-14 03:03 UTC, ryanpdx commented on olaf/bpe/main_pybind.cpp
> +}
Remove

2023-11-14 03:03 UTC, ryanpdx commented on olaf/bpe/testing/pixel_check.py
> +# (program utilizes PIL)
Use block comment style

2023-11-14 03:03 UTC, ryanpdx commented on olaf/bpe/testing/pixel_check.py
> +    pixel_check(file1, file2)
Use argparser

2023-11-14 04:25 UTC, ryanpdx commented
If you can, please try to squash some of your commits and update your comments to better reflect what changed in the commits. 

Also run `black` and `isort` on your `.py` files.

2023-11-14 05:30 UTC, kk60503 commented on olaf/bpe/testing/test_bpe.py
> +
Sorry Ryan, did you want me to remove lines 86-down at this part?

2023-12-03 23:59 UTC, closed without merging